### ISSUE TITLE
Dúvida no última regra

### ISSUE THREAD

**Issue by DanielAlmeidaJoao** [premium-minds/summer-internship-exercise-2022#7]
A ]ultima regra diz: Passar por cima de um ponto que já foi 'usado': como [7,3] que passou por cima do 5, sendo que este já tinha sido utilizado.
De acordo com a última regra, porque que no exemplo não temos a sequência [3,7] ?
Será possível fornecerem mais exemplos que ajudem a perceber o enunciado?

**Comment by amadoandre** [comment]
Boas,
No exemplo dado, a sequência passa por cima do 5 no movimento 7-3 sendo que a sequência acaba no 3 e o 5 já estava na sequência antes.

Para tentar explicar melhor a regra:
 Caso tentes fazer o caminho do 1 para o 3 apenas o podes fazer caso o 2 já esteja antes na tua sequência.
Caso tentes fazer o caminho do 1 para o 9 apenas o podes fazer caso o 5 já esteja antes na sequência .
O mesmo acontece com o caminho 1-7 ,onde o ponto 4 tem que estar na sequência

**Comment by DanielAlmeidaJoao** [comment]
No countPatternsFrom(3, 2), há o caminho [3,5], porque que não há o caminho [3,7] se o caminho [3,7] passa pelo 5 que já foi usado ?

**Comment by amadoandre** [comment]
Esse exemplo começa no 3, logo não pode ir para o 7 por o 5 ainda não foi utilizado (utilizado no mesmo caminho) como só tem 2 de tamanho não vai ter nenhum salto.
Quando se diz utilizado é utilizado na mesma sequência e não numa outra sequência.

**Comment by DanielAlmeidaJoao** [comment]
Percebi, obrigado.
